all:
	g++ -Wall -std=c++17 -O3 -I. -I../include -o main main.cpp \
	test_serialize_uint.cpp   \
	test_serialize_int.cpp    \
	test_serialize_string.cpp \
	test_serialize_float.cpp  \
	test_serialize_bool.cpp   \
	test_serialize_vector.cpp \
	test_serialize_tuple.cpp  \
	test_serialize_pair.cpp

clean:
	rm main
