all:
	g++ -Wall -std=c++17 -O3 -I. -I../include -o main main.cpp \
	test_serialize_uint.cpp   \
	test_serialize_int.cpp    \
	test_serialize_string.cpp \
	test_serialize_float.cpp  \
	test_serialize_bool.cpp   \
	test_serialize_array.cpp \
	test_serialize_vector.cpp \
	test_serialize_tuple.cpp  \
	test_serialize_pair.cpp   \
	test_serialize_enum_class.cpp \
	test_serialize_nested_struct.cpp \
	test_serialize_map.cpp \
	test_serialize_optional.cpp \
	test_deserialize_uint.cpp \
	test_deserialize_int.cpp \
	test_deserialize_string.cpp \
	test_deserialize_float.cpp \
	test_deserialize_bool.cpp \
	test_deserialize_array.cpp \
	test_deserialize_vector.cpp \
	test_deserialize_tuple.cpp \
	test_deserialize_pair.cpp \
	test_deserialize_map.cpp \
	test_deserialize_enum_class.cpp \
	test_deserialize_optional.cpp

clean:
	rm main
